policy: "PolicyTwist"
replay_buffer: "ReplayBufferTwist"
visual_embedding_dim: 2394
resnet_visual_embedding_dim: 1128
proprio_dim: 13
action_dim: 7
action_dim_abs_rot: 13
learning_rate: 1e-4
weight_decay: 0.0
batch_size: 2
sequence_len: 25
num_epochs: 500
buffer_capacity: 2000
steps: 200000
bptt_chunk: 25