visual_embedding_dim: 2394
resnet_visual_embedding_dim: 8
proprio_dim: 13
action_dim: 7
action_dim_abs_rot: 13
learning_rate: 1e-5
weight_decay: 3e-4
batch_size: 2
sequence_len: 25
num_epochs: 500
buffer_capacity: 200
steps: 100000
