"model_path": "/home/mokhtars/Documents/isaac-fmm/models/fmm_full.usd"
"object_path": "/home/mokhtars/Documents/bc_network/bc_files/simple_bowl.usd"
"fps": 40
"mesh_dir": "/home/mokhtars/Documents/bc_network/bc_files/bowl.h5"